[[actions]]
name = "Play"
path = "Blades of Exile.exe"
platform = "windows"

[[actions]]
name = "Play, Logging Everything To Help The Devs Fix Bugs"
path = "Blades of Exile.exe"
platform = "windows"
args = ["--record", "log"]

[[actions]]
name = "Play"
path = "Blades of Exile.app"
platform = "osx"

[[actions]]
name = "Play, Logging Everything To Help The Devs Fix Bugs"
path = "Blades of Exile.app"
platform = "osx"
args = ["--record", "log"]